language: ruby
bundler_args: --without development

rvm:
  - 2.1.1

matrix:
  exclude:
    - rvm: 1.8.7
      env: PATTERN=synchrony
    - rvm: jruby-19mode
      env: PATTERN=synchrony

script:
  - bundle exec rake pattern
